---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: ashoksun01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
      tier: backend
  template:
    metadata:
      labels:
        app: redis-server
        tier: backend
    spec:
      containers:
        - name: redis
          image: redis:6.2
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 700Mi
          command: ["redis-server"]
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
